name: CI

on:
  pull_request:
    paths:
      - '**/*'

jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in $ALL_CHANGED_FILES; do
            echo "$file was changed"
          done

      - name: Post comment to pull request
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const changedFiles = process.env.ALL_CHANGED_FILES || '';
            const commentBody = `### Changed Files in this Pull Request ###\n${changedFiles.split('\n').filter(Boolean).join('\n')}\n\n`;

            const { owner, repo, number } = context.issue;
            await github.issues.createComment({ owner, repo, issue_number: number, body: commentBody });
