name: CI

on:
  pull_request:
    paths:
      - '**/*'

jobs:
  file-list:
    runs-on: ubuntu-latest
    name: Changed files - PR Desc.
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in $ALL_CHANGED_FILES; do
            echo "$file was changed"
          done

      - name: Update PR description
        run: |
          changedFiles="${{ steps.changed-files.outputs.all_changed_files }}"
          prNumber="${{ github.event.number }}"
          
          # Escape double quotes in JSON
          changedFiles="${changedFiles//\"/\\\"}"
          
          # Update the pull request description with the new list of changed files
          curl -sSL \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -X PATCH -d "{\"body\":\"## Changed Files in this Pull Request ##\n${changedFiles}\"}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$prNumber"
