name: CI

on:
  pull_request:
    paths:
      - '**/*'

jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in $ALL_CHANGED_FILES; do
            echo "$file was changed"
          done

      - name: Update PR description
        run: |
          changedFiles="${{ steps.changed-files.outputs.all_changed_files }}"
          prNumber="${{ github.event.number }}"
          currentDescription=$(curl -sSL -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/pulls/$prNumber" | jq -r .body)

          # Escape double quotes in JSON
          changedFiles="${changedFiles//\"/\\\"}"

          # Construct the JSON payload with proper formatting
          newDescription='{"body":"### Changed Files in this Pull Request ###\n'"$changedFiles"'\n\n'"$currentDescription"'"}'

          # Use echo to ensure proper JSON formatting
          echo "${newDescription}" > new_description.json

          curl -sSL \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -X PATCH -d "@new_description.json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$prNumber"
