name: 🚀 Deploy

on:
  pull_request:
    types: 
      - synchronize
      - opened
      - labeled
    paths:
      - '**/*'
permissions:
  contents: write
jobs:
  comment-on-changes:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Get changed files
      id: get_changes
      run: |
        echo "Changed files:"
        git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changed_files.txt
        cat changed_files.txt
        echo "::set-output name=changed_files::$(cat changed_files.txt)"

    - name: Add comment with changed files
      run: |
        changed_files="${{ steps.get_changes.outputs.changed_files }}"
        if [ -n "$changed_files" ]; then
          echo "### Files Changed in this Pull Request ###"
          echo "$changed_files"
          echo "### End of Changes ###"

          # Debugging output
          echo "Repository: ${{ github.repository }}"
          echo "Pull Request Number: ${{ github.event.number }}"
          echo "Token: ${{ secrets.GITHUB_TOKEN }}"

          # Add a comment to the pull request
          token="${{ secrets.GITHUB_TOKEN }}"
          repository="${{ github.repository }}"
          pull_request="${{ github.event.number }}"
          body=$(echo -e "### Files Changed in this Pull Request ###\n$changed_files\n### End of Changes ###")
          curl -sSL -H "Authorization: token $token" -X POST -d '{"body":"'"$body"'"}' "https://api.github.com/repos/$repository/issues/$pull_request/comments"
        else
          echo "No files changed in this pull request."
        fi
  web-deploy:
    name: 🎉 Deploy
    if: contains(github.event.pull_request.labels.*.name, 'ready for review')
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ftp.bgsandbox.com
        username: willelder@bgsandbox.com
        password: ${{ secrets.ftp_password }}
        port: 21
        local-dir: ./dist/
        server-dir: suicide-prevention.bgsandbox.com/
        exclude: |
          **/.DS_Store
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/assets/sass/**
          **/uswds/img/material-icons-deprecated/**
          **/uswds/img/material-icons/*
  lighthouse:
    name: 👀 Lighthouse Scan
    runs-on: ubuntu-latest
    needs: web-deploy
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@master
    - name: 👀 Lighthouse
      uses: foo-software/lighthouse-check-action@master
      with:
        urls: 'https://suicide-prevention.bgsandbox.com/index.html'
        device: all  
        awsAccessKeyId: ${{ secrets.LIGHTHOUSE_CHECK_AWS_ACCESS_KEY_ID }}
        awsBucket: ${{ secrets.LIGHTHOUSE_CHECK_AWS_BUCKET }}
        awsRegion: ${{ secrets.LIGHTHOUSE_CHECK_AWS_REGION }}
        awsSecretAccessKey: ${{ secrets.LIGHTHOUSE_CHECK_AWS_SECRET_ACCESS_KEY }}
        gitAuthor: ${{ github.actor }}
        gitBranch: ${{ github.ref }}
        gitHubAccessToken: ${{ secrets.GITHUB_TOKEN }}
        sha: ${{ github.sha }}
        slackWebhookUrl: ${{ secrets.LIGHTHOUSE_CHECK_WEBHOOK_URL }}
