on: 
  push:
    branches:
      - main
name: 🚀 Deploy to Sandbox
jobs:
  web-deploy:
        name: 🎉 Deploy
        runs-on: ubuntu-latest
        steps:
        - name: 🚚 Get latest code
          uses: actions/checkout@v3
        
        - name: 📂 Sync files
          uses: SamKirkland/FTP-Deploy-Action@v4.3.4
          with:
            server: ftp.bgsandbox.com
            username: willelder@bgsandbox.com
            password: ${{ secrets.ftp_password }}
            port: 21
            local-dir: ./dist/
            server-dir: suicide-prevention.bgsandbox/
            exclude: |
              **/.DS_Store
              **/.git*
              **/.git*/**
              **/node_modules/**
              **/assets/sass/**
              **/uswds/img/material-icons-deprecated/**
              **/uswds/img/material-icons/*